apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: harbor
  name: harbor-tls
  namespace: harbor
spec:
  dnsNames:
  - harbor.papermint.io
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: zerossl
  secretName: harbor-tls
  usages:
  - digital signature
  - key encipherment