apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    meta.helm.sh/release-name: harbor-application 
    meta.helm.sh/release-namespace: harbor
  labels:
    app.kubernetes.io/managed-by: Helm
  name: harbor-application-selfsigned-issuer
  namespace: harbor
spec:
  selfSigned: {}

